inherit_from: .rubocop_todo.yml

Documentation:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'test/**/*.rb'
