version: '2'

services:
  common:
    build: .
    volumes:
      - .:/bowling-api
    image: bowling-api
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres

  web:
    extends:
      service: common
    command: rails s -b 0.0.0.0
    depends_on:
      - postgres
    ports:
      - 3000:3000

  test:
    extends:
      service: common
    command: bash -c "rubocop && rspec"
    environment:
      - RAILS_ENV=test
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:11.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
